### PR TITLE
Bump libtar to the latest version in master

### PR DESCRIPTION
**Pull request by JanuszL**
- adds a handful of CVEs patches on top of 1.20.0

Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JanuszL** [comment]
Hi @conda-forge-admin, @egpbos,

I think this is ready for review and merge.

**Comment by egpbos** [comment]
Ah, this seems great, thanks. I'm wondering slightly whether the version number should be different, since apparently this package is in sort of maintenance mode and no releases will be made anymore. Something like "1.2.20-master" maybe. What do you think @JanuszL? I don't feel strongly, so I'll just merge for now and we can change later if we like.

**Review by egpbos — COMMENTED** [review]
LGTM!

**Comment by JanuszL** [comment]
@egpbos - I don't have strong feelings as well. Up to you.

**Pull request merged**
